### ISSUE TITLE
Design layout for the website

### ISSUE THREAD

**Issue by asdofindia** [MozINadvocacy/MozINadvocacy.github.io#1]
This site will go live on advocacy.mozillaindia.org and should include a call to action to sign up for email newsletter.

There should also be latest posts from Mozilla India blog in policy advocacy category displayed on the site.

[Google's Take Action site](https://www.google.com/takeaction/) could be used as a reference.

Assigned to @MozINadvocacy/ui

**Comment by pmjcreations** [comment]
Hello @asdofindia, can we have a call with all the stakeholders for discussing about the Web site and its scope?

**Comment by asdofindia** [comment]
Yes. We can discuss this probably in our next community call.

**Comment by tripad** [comment]
Awesome - Lets get started then

**Comment by tsl143** [comment]
Any updates on this?
I will be more than glad to put my efforts in this :)

**Comment by asdofindia** [comment]
We could copy the [mozilla advocacy website](https://advocacy.mozilla.org/)

**Comment by pmjcreations** [comment]
It would be really helpful if we can have a brainstorming session to discuss about the scope of this site and the content what we are going to deliver through this.

**Comment by tripad** [comment]
+1
We need to first discuss scope of the website so that we have a clear purpose of the website

**Comment by asdofindia** [comment]
Closing as the task force doesn't exist now.
